
image: node:10.5.0

before_script:
    - npm install

stages:
    - build
    - test
    - deploy

build:
  stage: build
  script:
    - npm install
    - npm run minifier

test:
  stage: test
  script:
    - npm run test


deploy-stage:
  stage: deploy
  script:
    - npm run deploy-stage
  only:
    - dev

deploy-prod:
    stage: deploy
    script:
      - npm run deploy-prod
    only:
      - master
