stages:
  - build
  - test


build:
  stage: build
  script:
    - echo "build th is"
    - hostname
    - mkdir builds
    - touch builds/data.txt
    - echo "true" > builds/data.txt
  artifacts:
    paths:
      - builds/

test:
  stage: test
  script:
    - echo "testingthgis is"
    - hostname
    - test -f builds/data.txt
    - grep "true" builds/data.txt
