# stages:
#     - build
#     - test
#     - deploy

# maven-build:
#   image: maven:3-jdk-11
#   stage: build
#   script: "mvn package -B"
#   artifacts:
#     paths:
#       - target/gitlab-ci-demo.jar

# image: alpine

# stages:
#   - compile
#   - test
#   - package

# compile:
#   stage: compile
#   script: 
#     - echo "Hello world 1" > file1.txt
#     - echo "Hello world 2" > file2.txt
#     - cat file1.txt file2.txt > compiled.txt
#   artifacts:
#     paths:
#     - compiled.txt
#     - file1.txt


# test:
#   stage: test
#   script: cat compiled.txt | grep -q 'Hello world'

# pack-gz:
#   stage: package
#   script: cat compiled.txt | gzip > packaged.gz
#   artifacts:
#     paths:
#     - packaged.gz
#     - file1.txt

# pack-iso:
#   stage: package
#   before_script:
#   - echo "ipv6" >> /etc/modules
#   - apk update
#   - apk add xorriso
#   script:
#   - mkisofs -o ./packaged.iso ./compiled.txt
#   artifacts:
#     paths:
#     - packaged-$CI_JOB_ID-$CI_COMMIT_SHORT_SHA.iso    


# stages:
#   - build
#   - runeeeeeee

# build-docker:
#   stage: build
#   image: docker:stable
#   only:
#     - main
#   services:
#     - docker:dind
#   before_script:
#     - docker login -u gitlab+deploy-token-1249784 -p ${ACCESS_TOKEN} registry.gitlab.com
#   script:
#     - docker build -t ${DOCKER_ENV_CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME} --build-arg branch=${CI_COMMIT_REF_NAME} .
#     - docker push ${DOCKER_ENV_CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}
    
# running:
#   stage: runeeeeeee
#   only: 
#     - main
#   before_script:
#     - docker login -u gitlab+deploy-token-1249784 -p ${ACCESS_TOKEN} registry.gitlab.com
#   script:
#     - docker run -p 3000:3000 --name test-ci registry.gitlab.com/runalsh/mymymy:main

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH != "main" && $CI_PIPELINE_SOURCE != "merge_request_event"
      when: never
    - when: always 

variables:
    imagerepo: docker.io/my-docker-id/myapp
    imagetag: v1.0

stages:
  - test
  - build
  - deploy

run_unit_test:
  stage: test
  tags:
    - shelltag
  image: node:17-alpine
  before_script:
    - echo "preparing tesdt"
  script:
    - echo "run unit test form microservice $MICRO_NAME"
    - npm version
  after_script:
    - echo "clean temp"

run_lint_test:
  stage: test
  tags:
    - dockeralpinprivetag
  before_script:
    - echo "preparing test data"
  script:
    - echo "run lint test"
  after_script:
    - echo "clean temp"   

build_image:
  stage: build
  tags:
    - shelltag
    - dockeralpinetag
  only:
    - main
  script:
    - echo "build docker image"
    - echo "tag docker image $imagerepo:$imagetag"


push_image:
  stage: build
  tags:
    - shelltag
    - dockeralpinetag
  script:
    - echo "push docker image $imagerepo:$imagetag to regisrty"

deploy_image:
  stage: deploy
  tags:
    - shelltag
    - dockeralpinetag
  script:
    - echo "run deploy $imagerepo:$imagetag to $DEPLOYMENT_ENVIROMENT using follow configuration file - $proper_file"
    - cat $proper_file






