#cloud-config
write_files:
 - path: "/opt/aws/amazon-cloudwatch-agent/etc/config.json"
   owner: "root:root"
   permissions: "'0644"
   content: |
        {
        "agent": {
                "metrics_collection_interval": 60,
                "run_as_user": "root"
        },
        "logs": {
                "logs_collected": {
                        "files": {
                                "collect_list": [
                                        {
                                        "file_path": "/actions-runner/_diag/*",
                                        "log_group_name": "/aws/ec2/epam-py-runner/",
                                        "log_stream_name": "{instance_id}-runner",
                                        "retention_in_days": 3
                                        },
                                        {
                                        "file_path": "/var/log/amazon/amazon-cloudwatch-agent/*",
                                        "log_group_name": "/aws/ec2/epam-py-runner/",
                                        "log_stream_name": "{instance_id}-cloudwatch-agent",
                                        "retention_in_days": 3
                                        },
                                        {
                                        "file_path": "/var/log/cloud-init*.log",
                                        "log_group_name": "/aws/ec2/epam-py-runner/",
                                        "log_stream_name": "{instance_id}-cloudinit",
                                        "retention_in_days": 3
                                        }
                                ]
                        }
                }
        },
        "metrics": {
                "aggregation_dimensions": [
                        [
                                "InstanceId"
                        ]
                ],
                "append_dimensions": {
                        "AutoScalingGroupName": "$${aws:AutoScalingGroupName}",
                        "ImageId": "$${aws:ImageId}",
                        "InstanceId": "$${aws:InstanceId}",
                        "InstanceType": "$${aws:InstanceType}"
                },
                "metrics_collected": {
                        "collectd": {
                                "metrics_aggregation_interval": 60
                        },
                        "cpu": {
                                "measurement": [
                                        "cpu_usage_idle",
                                        "cpu_usage_iowait",
                                        "cpu_usage_user",
                                        "cpu_usage_system"
                                ],
                                "metrics_collection_interval": 60,
                                "resources": [
                                        "*"
                                ],
                                "totalcpu": false
                        },
                        "disk": {
                                "measurement": [
                                        "used_percent",
                                        "inodes_free"
                                ],
                                "metrics_collection_interval": 60,
                                "resources": [
                                        "*"
                                ]
                        },
                        "diskio": {
                                "measurement": [
                                        "io_time",
                                        "write_bytes",
                                        "read_bytes",
                                        "writes",
                                        "reads"
                                ],
                                "metrics_collection_interval": 60,
                                "resources": [
                                        "*"
                                ]
                        },
                        "mem": {
                                "measurement": [
                                        "mem_used_percent"
                                ],
                                "metrics_collection_interval": 60
                        },
                        "netstat": {
                                "measurement": [
                                        "tcp_established",
                                        "tcp_time_wait"
                                ],
                                "metrics_collection_interval": 60
                        },
                        "statsd": {
                                "metrics_aggregation_interval": 60,
                                "metrics_collection_interval": 10,
                                "service_address": ":8125"
                        },
                        "swap": {
                                "measurement": [
                                        "swap_used_percent"
                                ],
                                "metrics_collection_interval": 60
                                }
                        }
                }
        }


package_update: true

package_upgrade: true

packages:
 - yum-utils
 - curl
 - mc
 - tar
 - wget
 - openssl
 - nano
 - nmon
 - jq
 - ncdu
 - amazon-linux-extras
 - net-tools
 - unzip
 - amazon-cloudwatch-agent
 
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAr53uTiK0O/sbacgMcsHGp2mL0XvjpxI9O6n2KOPduFbmwKF/ZxLZm6nR1K6Dkj5aeg+BEFft1lrkh08ubJCYkF7/5vXy5dlzlLokCwc3aEOIIxD2WsOaFizmiy/b3KE16bvpkM7WzydlW6LyTaF3BoAikiw5D5IibroSij2mFWGVieXxXJSyryu+xmsNqGywuKc+4DjoaqEJJooBU53OdTkg8RGeN4dCrEWbJIc7agl5MDaBpL8aO6vH4OuGM7u3UFCTgDe6KRlK+bgYs4QEqb55RiNIp0vAOET4jH2QBhP489+5R1V6B/ozx2n0rDo3F3Hrha2Cp835KGoJVl2Gmw== rsa-key-20211028

runcmd:
  - curl https://freedns.afraid.org/dynamic/update.php?U2NnUkQ5TlYydkk0Wm5UeEVRT0c6MTk3NTIyNDc=
  - timedatectl set-timezone Europe/Moscow
  - export PATH="/usr/local/bin:$PATH"


# python/pip install
  - sudo  amazon-linux-extras enable python3.8
  - sudo yum install python38 -y
  - sudo wget https://bootstrap.pypa.io/get-pip.py
  - sudo alias python3=python3.8
  - sudo python3 get-pip.py
  - sudo python3 -m pip install --upgrade pip

# install terraform
  - sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
  - sudo yum -y install terraform

# install nodejs for terraform  
  - sudo curl -sL https://rpm.nodesource.com/setup_14.x | sudo bash -
  - sudo yum install nodejs -y

#install aws cli
  - sudo url "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  - sudo unzip awscliv2.zip
  - sudo  ./aws/install --bin-dir /usr/bin --install-dir /usr/local/aws-cli --update

# install helm
  - sudo curl -sSL https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
  - sudo mv /usr/local/bin/helm /usr/bin/helm

# install kubectl
  - sudo curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
  - sudo chmod +x ./kubectl
  - sudo mv ./kubectl /usr/bin/kubectl
  # - sudo curl -o /usr//bin/kubectl -LO "https://dl.k8s.io/release/v1.23.6/bin/linux/amd64/kubectl"
  # - sudo chmod +x /usr/bin/kubectl



